# Site settings
title: Design.UCSD
url: "http://designucsd.github.io"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed
  sass_dir: public/_scss

include:
- public/css
- public/js

# Show future events/posts
future: true

timezone: America/Los_Angeles

highlighter: rouge